apiVersion: v1
kind: Secret
metadata:
  name: basic-ssh-pass 
  annotations:
    tekton.dev/git-0: https://github.com/TiagoAvelino/HelloWordProject.git
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: 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