apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-quarkus
  labels:
    app: my-java-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-java-quarkus
  template:
    metadata:
      labels:
        app: my-java-quarkus
    spec:
      containers:
        - name: my-java-quarkus
          image: default-route-openshift-image-registry.apps-crc.testing/development/hello-quarkus
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "150m"