kind: Service
  apiVersion: v1
  metadata:
    name: my-java-quarkus
  spec:
    type: NodePort
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: my-java-quarkus